// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about-img': string;
  'left': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
