// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-wrapper': string;
  'drawer-bg': string;
  'main-container': string;
  'mobile-menu-container': string;
  'scroll-container': string;
  'scroll-scroller': string;
}
export const cssExports: CssExports;
export default cssExports;
