// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'face': string;
  'logo': string;
  'main': string;
  'onme': string;
  'phone': string;
  'tel': string;
}
export const cssExports: CssExports;
export default cssExports;
