// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentbox': string;
  'count': string;
  'infoContentbox': string;
  'infobox': string;
  'main': string;
  'outbox': string;
  'swiperPagination': string;
  'swiperbox': string;
}
export const cssExports: CssExports;
export default cssExports;
