// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-main': string;
  'app-main-container': string;
}
export const cssExports: CssExports;
export default cssExports;
