// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-header': string;
  'app-header-container': string;
  'app-header-setting': string;
  'header-right': string;
  'logo': string;
  'logoBox': string;
  'menu-switch': string;
}
export const cssExports: CssExports;
export default cssExports;
