// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'international': string;
  'open': string;
  'openIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
