// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'maxMainWidth': string;
  'menuActiveText': string;
  'menuBg': string;
  'menuBgHover': string;
  'menuHeight': string;
  'menuText': string;
  'responsiveWidth': string;
}
export const cssExports: CssExports;
export default cssExports;
