// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aboutBannerContainer': string;
  'aboutSwiper': string;
  'imgBg': string;
  'main': string;
  'swiperPagination': string;
}
export const cssExports: CssExports;
export default cssExports;
